### Sign up new user request
POST http://localhost:3001/api/user/sign-up
Content-Type: application/json

{
  "username": "jac32gtggtgt32k123",
  "password": "password"
}

### Make a Login request
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "username": "tommy",
  "password": "password"
}

### Fetch without token ( not logged in, shouldnt be able to access )
GET http://localhost:3001/api/user/test
### Test with token
GET http://localhost:3001/api/user/test
Authorization: Bearer 
### Delete token by logging out
POST http://localhost:3001/api/user/logout

###
GET http://localhost:3001/api/catalog/all-cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsInVzZXJuYW1lIjoidG9tbXkiLCJpYXQiOjE2ODI0Mjc3MDYsImV4cCI6MTY4MzcyMzcwNn0.twRZreet83xDiru8Sa3EAoI2u_mQkfQSs337H2EfC5I